// Generated by bundle.mjs — do not edit by hand.
// Re-generated every time `node bundle.mjs` runs.
import * as React    from 'react';
import * as ReactDOM from 'react-dom/client';
import htm           from 'htm';
import CodeMirror    from 'codemirror';
import 'codemirror/mode/css/css';
import 'codemirror/mode/xml/xml';
import 'codemirror/mode/htmlmixed/htmlmixed';
import cmCss         from 'codemirror/lib/codemirror.css';
import cmTheme       from 'codemirror/theme/material-darker.css';
import widgetCss     from './widget.css';

// ── Style injection ───────────────────────────────────────────────────────────
// Injected once; idempotent via the id check.

function ensureStyles() {
  if (document.getElementById('wh-embed-styles')) return;
  var s = document.createElement('style');
  s.id = 'wh-embed-styles';
  // Override the @font-face src to the absolute GitHub Pages URL so the font
  // loads correctly when embedded in any third-party page.
  var fontOverride = "@font-face{font-family:'Hello Gorgeous';src:url('https://parttimenerd.github.io/svg-writing-animation/HelloGorgeous-Script.ttf') format('truetype');font-display:swap;}";
  s.textContent = fontOverride + widgetCss + cmCss + cmTheme;
  document.head.appendChild(s);
}

// ── Widget HTML lookup ────────────────────────────────────────────────────────
// Inlined at build time by bundle.mjs.

var WIDGETS = __WIDGET_HTML_MAP__;

// ── Core widget logic ─────────────────────────────────────────────────────────
// The IIFE from widget.js accepts its deps as parameters so it works both
// via CDN globals (index.html) and as a bundle import here.

/* __WIDGET_JS__ */

// ── Public API ────────────────────────────────────────────────────────────────

function initEmbed() {
  ensureStyles();
  document.querySelectorAll('[data-wh-widget]').forEach(function (el) {
    var key = el.getAttribute('data-wh-widget');
    var html = WIDGETS[key];
    if (!html) { console.warn('WritingWidget: unknown widget', key); return; }
    var wrapper = document.createElement('div');
    wrapper.innerHTML = html;
    var widgetEl = wrapper.firstElementChild;
    el.replaceWith(widgetEl);
    // Boot just this widget — mirror the Widget() call in widget.js.
    widgetEl.dispatchEvent(new CustomEvent('wh:init', { bubbles: true }));
  });
}

window.WritingWidget = { init: initEmbed };

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initEmbed);
} else {
  initEmbed();
}
